try{console.log("Hello Console.")}catch(e$$5){window.console={};for(var cMethods="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),i=0;i<cMethods.length;i++)console[cMethods[i]]=function(){}}
(function(c){window.GuruMap=function(e){var b=this,a={zoom:4,centerLat:38.7902935,centerLng:-97.64023729999997,mapHeight:500,fitMarkers:!1,contId:"gmapCont",dataCont:".locationList",dataBlock:".locationItem",dataAttr:"location-data",locationKey:"location_address",fallbackLocationKey:"mailing_address",fallbackOverrideKey:!1,markerImageKey:!1,zoomControlStyle:"DEFAULT",streetViewControl:!1,scrollwheel:!1,mapTypeId:"ROADMAP",markerScale:0.5,blocksAreClickable:!1,scrollToMapOnClick:!1,scrollSpeed:500,
directionsLink:!1,globalInitID:"GuruMapInit"},d;for(d in e)a[d]=e[d]||a[d];for(d in a)b[d]=a[d];b.loadingGoogle=!1;b.setupConstants=function(){if(typeof google!=="undefined")return window[b.globalInitID]&&(window[b.globalInitID]=void 0),b.loadingGoogle=!1,b.infowindow=new google.maps.InfoWindow,b.directionsService=new google.maps.DirectionsService,b.directionsDisplay=new google.maps.DirectionsRenderer,b.directionsDisplay.setMap(null),b.geocoder=new google.maps.Geocoder,b.center=null,b.cont=null,b.map=
null,b.form=null,b.startAddy="",b.endAddy="",b.currentRoute=null,b.confirmBttn=null,b.dblclickListener=null,b.data=[],b.markers=[],b.init();else if(!b.loadingGoogle){b.loadingGoogle=!0;window[b.globalInitID]=b.setupConstants;var a=document.createElement("script");a.type="text/javascript";a.src="http://maps.googleapis.com/maps/api/js?sensor=false&callback="+b.globalInitID;document.body.appendChild(a)}};b.init=function(){b.setupMarkerData();b.setupMap();b.setupMarkers()};b.setupMap=function(){b.cont=
document.getElementById(b.contId);c(b.cont).height()||c(b.cont).height(b.mapHeight);b.center=new google.maps.LatLng(b.centerLat,b.centerLng);b.map=new google.maps.Map(b.cont,{center:b.center,zoom:b.zoom,zoomControlOptions:{style:google.maps.ZoomControlStyle[b.zoomControlStyle]},streetViewControl:b.streetViewControl,scrollwheel:b.scrollwheel,mapTypeId:google.maps.MapTypeId[b.mapTypeId]})};b.setupMarkers=function(){if(b.data.length){var a=new google.maps.LatLngBounds;c.each(b.data,function(f){var d=
this,e=b.fallbackOverrideKey&&d[b.fallbackOverrideKey]&&d[b.fallbackLocationKey]?d[b.fallbackLocationKey]:d[b.locationKey]||d[b.fallbackLocationKey];e&&b.geocoder.geocode({address:b.stripTags(e)},function(e,l){if(l===google.maps.GeocoderStatus.OK){b.markers[f]=new google.maps.Marker({map:b.map,position:e[0].geometry.location,item:d});if(b.markerImageKey&&d[b.markerImageKey]){var h=d[b.markerImageKey],j=Math.floor(h.width*b.markerScale),h=Math.floor(h.height*b.markerScale);b.markers[f].setIcon(new google.maps.MarkerImage(d[b.markerImageKey].src,
new google.maps.Size(j,h),new google.maps.Point(0,0),new google.maps.Point(j/2,h/2),new google.maps.Size(j,h)))}google.maps.event.addListener(b.markers[f],"click",b.handleMarkerClick);b.blocksAreClickable&&c(d.DOM).attr({markerIndex:f}).mousedown(b.handleBlockClick).find("a").click(b.preventBlockLinks);b.fitMarkers&&(a.extend(b.markers[f].position),b.map.fitBounds(a))}else alert("Geocode was not successful for the following reason: "+l)})})}};b.preventBlockLinks=function(a){a.preventDefault()};b.handleBlockClick=
function(){var a=b.markers[c(this).attr("markerIndex")];b.handleMarkerClick.apply(a,[{latLng:a.position}]);b.scrollToMapOnClick&&(a=c(b.cont).closest("section").offset(),(c("body").scrollTop()||c("html").scrollTop())>a.top&&c("html, body").stop(!1,!1).animate({scrollTop:a.top},b.scrollSpeed))};b.handleMarkerClick=function(){var a='<div class="mapInfoDom">'+c(this.item.DOM).html();if(b.directionsLink){var d="http://maps.google.com/maps?saddr=&daddr="+this.item[b.locationKey].replace(/ /g,"+").replace(/\n/g,
",+");a+='<a class="directionsLink" href="'+d+'" title="Get directions to this site" target="_blank">Get Driving Directions</a>'}a+="</div>";b.infowindow.setContent(a);b.infowindow.open(b.map,this)};b.setupMarkerData=function(){return c(b.dataCont).find(b.dataBlock).each(function(){var a=JSON.parse(c(this).attr(b.dataAttr));a.DOM=this;b.data.push(a)})};b.stripTags=function(a){return typeof a!=="string"?!1:a.replace(/<([^>]+)>/g,"").replace(/\n|\r/g," ")};b.setupConstants();return b}})(jQuery);
(function(c){var e=function(b){var a={screen_name:"hicarlosangon",container_selector:".twitter-feed",include_rts:!0,include_entities:!0,trim_user:!1,tweet_limit:3,trans_time:250,interval:45E3,local_url:Guru.TemplateUrl+"/twitter/twitter-feed.php",api_url:"http://api.twitter.com/1/statuses/user_timeline.json"},d;for(d in b)a[d]=b[d]||a[d];for(d in a)this[d]=a[d];this.container=[];this.REQUESTS=[];this.TWEETS={};this.TWEETS_ON_PAGE=[];this.SINCE_ID=null;this.FIRST_CALL=!0;this.TIMEOUT=null;this.init()};
e.prototype.init=function(){this.container=c(this.container_selector);return!this.container.length?!1:this.makeApiCall()};e.prototype.makeLink=function(b,a,d){return'<a href="'+b+'"'+(d?' target="_blank"':"")+">"+a+"</a>"};e.prototype.makeApiCall=function(){var b=this,a=null,d=function(a){a.entities&&a.entities.urls.length&&c.each(a.entities.urls,function(){a.text=a.text.replace(this.url,b.makeLink(this.expanded_url,this.url,!0))});return a.text},g=function(f){if(f===b.tweet_limit)return!1;b.TWEETS[this.id]||
(b.TWEETS[this.id]=this,b.TWEETS_ON_PAGE.length>=b.tweet_limit&&b.TWEETS_ON_PAGE.shift().slideUp(b.trans_time,function(){console.log(c(this),c(this).siblings().length);c(this).siblings().length?c(this).remove():c(this).parent().remove()}),a&&(f=c("<div />",{html:d(this)}).addClass("tweet").hide().appendTo(a),f.slideDown(b.trans_time),b.TWEETS_ON_PAGE.push(f)))};return b.REQUESTS.push(c.ajax({url:b.local_url+"?",data:{screen_name:b.screen_name,api_url:b.api_url+"?"+b.makeRequestStr()},async:!0,dataType:"json",
error:function(a,d,c){console.log("something went wrong with the twitter widget",a,d,c,b.REQUESTS)},success:function(d){if(b.FIRST_CALL)b.FIRST_CALL=!1;if(d.length)a=c("<div />").addClass("tweetBlock").prependTo(b.container),c.each(d,g),b.SINCE_ID=d[0].id},complete:function(){b.container.removeClass("loading");b.REQUESTS.pop();return b.TIMEOUT=setTimeout(function(){b.makeApiCall.call(b)},b.interval)}}))};e.prototype.makeRequestObj=function(){return{screen_name:this.screen_name,include_rts:this.include_rts,
include_entities:this.include_entities,trim_user:this.trim_user}};e.prototype.makeRequestStr=function(){var b=this.makeRequestObj(),a="",d;for(d in b)a+="&"+d+"="+b[d];return a};window.GuruTwitter=e})(jQuery);
(function(c){var e=function(a){var b={container:[],slider:[],transition_time:500,timeout_time:2E3,vertical:!1},c;for(c in a)b[c]=a[c]||b[c];for(c in b)this[c]=b[c];this.current_slide=[];this.current_top=this.current_left=0;this.running=!1;this.timeout_id=null;this.init()};e.prototype.init=function(){if(!this.container.length||!this.slider.length||!this.slider.children().length)return!1;this.running=!0;this.current_slide=this.slider.children().first();this.current_left=this.getCenter()-this.getSlideCenter();
this.moveSlides()};e.prototype.getCenter=function(){return Math.floor(this.container.width()/2)};e.prototype.getSlideCenter=function(){return Math.floor(this.current_slide.outerWidth()/2)};e.prototype.moveSlides=function(){var a=this,b=this.vertical?{top:this.current_top}:{left:this.current_left};return a.slider.stop(!0,!0).animate(b,this.transition_time,function(){a.timeoutFunction.call(a)})};e.prototype.shiftSlide=function(){var a=this.slider.children().first(),b=a.outerWidth(),c=a.outerHeight();
!this.vertical&&this.current_left+b<=0?(a.appendTo(this.slider),this.current_left+=b,this.slider.css({left:this.current_left})):this.current_top+c<=0&&(a.appendTo(this.slider),this.current_top+=c,this.slider.css({top:this.current_top}))};e.prototype.setNewLeft=function(){return this.getCenter()-(this.current_slide.position().left+this.getSlideCenter())};e.prototype.setNewTop=function(){return this.current_slide.position().top*-1};e.prototype.timeoutFunction=function(){var a=this;a.shiftSlide();a.current_slide=
a.current_slide.next().length?a.current_slide.next():a.slider.children().first();a.vertical?a.current_top=a.setNewTop():a.current_left=a.setNewLeft();a.timeout_id=setTimeout(function(){a.moveSlides.call(a)},a.timeout_time)};window.GuruSlider=e;var b=function(a){var b={sliders:[],container_selector:"#slider",slider_selector:".slides",transition_time:500,timeout_time:2E3},c;for(c in a)b[c]=a[c]||b[c];for(c in b)this[c]=b[c];this.init()};b.prototype.init=function(){if(this.sliders.length)for(var a=0,
b=this.sliders.length;a<b;a++)this.sliders[a].container=c(this.sliders[a].container_selector),this.sliders[a].slider=this.sliders[a].container.find(this.sliders[a].slider_selector),this.sliders[a]=new e(this.sliders[a]);else{var g=this;c(g.container_selector).each(function(){g.sliders.push(new e({container:c(this),slider:c(this).find(g.slider_selector),transition_time:g.transition_time,timeout_time:g.timeout_time}))})}};window.GuruSliderController=b})(jQuery);
(function(c){var e=function(b){var a=this,d={contID:"rotator",sliderClass:"slides",controlsClass:"controls",nextText:">>",prevText:"<<",z:1,transitionTime:1E3,gidAtt:"gid",timeoutTime:7500,showControls:!1,linkTo:!1,linkClickCallback:function(){},autoRotate:!1,appendControlsTo:!1},e;for(e in b)d[e]=b[e]||d[e];for(e in d)a[e]=d[e];a.container=null;a.slider=null;a.slides=null;a.controls=null;a.sliderTimeout=null;a.currentSlide=[];a.nextSlide=null;a.binaryControls=null;a.RUNNING=!1;a.other=!1;a.init=
function(){if(c("#"+a.contID).length)a.container=c("#"+a.contID),a.slider=a.container.find("."+a.sliderClass),a.slides=a.slider.children(),a.controls=a.makeControls(),a.controls.children().last().addClass("active"),a.slides.last().addClass("active"),a.currentSlide=a.slides.last().fadeTo(a.transitionTime,1),a.slides.not(".active").fadeOut(0),c(window).resize(a.onResize),a.onResize(),a.RUNNING=!0;return a};a.isRunning=function(){return a.RUNNING};a.onResize=function(){if(a.container.is(":visible")){if(!a.sliderTimeout&&
a.autoRotate)a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime)}else if(a.sliderTimeout&&a.autoRotate)clearTimeout(a.sliderTimeout),a.sliderTimeout=null};a.makeControls=function(){var b=c("<div />").addClass(a.controlsClass);a.slides.each(function(d){var e=c(this).attr(a.gidAtt);c("<div />",{text:d+1}).attr(a.gidAtt,e).click(a.ctrlClickHandle).appendTo(b)});(!a.showControls||a.showControls==="binary")&&b.hide();if(a.showControls==="binary")a.binaryControls=a.makeBinaryControls();a.appendControlsTo&&
c(a.appendControlsTo).length?b.appendTo(a.appendControlsTo):b.appendTo(a.container);return b};a.makeBinaryControls=function(){var b=c("<div />").addClass(a.controlsClass);c("<span />",{text:a.prevText}).addClass("prev").click(a.binaryCtrlClickHandle).appendTo(b);c("<span />",{text:a.nextText}).addClass("next").click(a.binaryCtrlClickHandle).appendTo(b);b.appendTo(a.container);return b};a.ctrlClickHandle=function(){var b=c(this).attr(a.gidAtt);a.slideChange(b);return a.linkClickCallback(b,a.linkTo)};
a.binaryCtrlClickHandle=function(){var b=c(this).hasClass("prev")?a.getPreviousSlide().attr(a.gidAtt):a.getNextSlide().attr(a.gidAtt);a.slideChange(b);return a.linkClickCallback(b,a.linkTo)};a.getNextSlide=function(){return a.currentSlide.next().length?a.currentSlide.next():a.currentSlide.parent().children().first()};a.getPreviousSlide=function(){return a.currentSlide.prev().length?a.currentSlide.prev():a.currentSlide.parent().children().last()};a.slideChange=function(b){var c=a.getControlByID(b);
if(!c.hasClass("active"))return a.sliderTimeout&&clearTimeout(a.sliderTimeout),a.z++,a.nextSlide=a.getSlideByID(b),a.fadeChange(),a.controls.find(".active").removeClass("active"),c.addClass("active"),a.autoRotate?a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime):!0};a.fadeChange=function(){if(!a.nextSlide)return!1;a.slider.find(a.currentSlide).stop(!1,!1);a.slides.not(a.nextSlide).stop(!0,!1);a.nextSlide.addClass("active").css({zIndex:a.z}).stop(!0,!0).fadeTo(a.transitionTime,1);a.slides.not(a.nextSlide).stop(!0,
!0).fadeOut(a.transitionTime).removeClass("active");a.currentSlide=a.nextSlide;a.nextSlide=null};a.getControlByID=function(b){return!b?!1:a.controls.find("["+a.gidAtt+'="'+b+'"]')};a.getSlideByID=function(b){return!b?!1:a.slider.find("["+a.gidAtt+'="'+b+'"]')};a.sliderTimeoutFunc=function(){return a.slideChange(a.getNextSlide().attr(a.gidAtt))};return a.init()};window.GuruRotator=e;window.GuruRotatorController=function(b){var a=this,d={rotatorsConfig:[],timeoutTime:7500},g;for(g in b)d[g]=b[g]||d[g];
for(g in d)a[g]=d[g];a.rotators={};a.sliderTimeout=null;a.init=function(){if(typeof a.rotatorsConfig==="object"&&a.rotatorsConfig.length)c.each(a.rotatorsConfig,a.startRotator),a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime);return a};a.startRotator=function(){if(this.linkTo)this.linkClickCallback=a.linkClickCallback;a.rotators[this.contID]=new e(this)};a.sliderTimeoutFunc=function(){clearTimeout(a.sliderTimeout);c.each(a.rotators,a.rotateInstance);return a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,
a.timeoutTime)};a.rotateInstance=function(){!this.autoRotate&&this.RUNNING&&this.container.is(":visible")&&this.slideChange(this.getNextSlide().attr(this.gidAtt));return!0};a.linkClickCallback=function(b,c){if(!b||!c)return!1;clearTimeout(a.sliderTimeout);var d=a.rotators[c];typeof d==="object"&&d.isRunning()&&d.slideChange(b);return a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime)};return a.init()}})(jQuery);(function(c){function e(){if(c("form.newsletter").length>0){var b=c("form.newsletter"),a=b.find("input"),d=b.find("button"),e=!1,f=function(f){f.preventDefault();var f=a.val(),j=Guru.TemplateUrl+"/mailchimp_subscribe.php",k=function(a,e){if(typeof a==="undefined"||!a)a="Well, something went wrong.";var f;c("<span />",{text:a}).addClass(!e?"mcError error":"mcError success").insertAfter(d);return setTimeout(function(){var a=b.find(".mcError");a.length&&a.fadeOut(900,function(){c(this).remove()})},2500)};
b.find(".mcError").remove();if(f==="")return k("We need an email address, please."),!1;e||(e=!0,c.get(j,"email="+f,function(a){e=!1;a=JSON.parse(a);if(a.error){var b=a.error;switch(!0){case a.error.indexOf("already subscribed")!==-1:b="That email's already on our list!";break;case a.error.indexOf("Invalid Email Address")!==-1:b="We need a proper email address, please."}return k(b)}return k("You have been signed up!",!0)}))};d.click(f);b.submit(f)}}c(document).ready(function(){c("html.ie").length?
Guru.ie=!0:Guru.ie=!1;c("html.lte8").length?Guru.lte8=!0:Guru.lte8=!1;typeof WebKitPoint!=="undefined"?Guru.webkit=!0:Guru.webkit=!1;new GuruRotator({transitionTime:750,timeoutTime:7E3,showControls:!0,autoRotate:!0});new GuruSliderController({sliders:[{container_selector:"#mainLeft .verticalSlider",slider_selector:".slides",timeout_time:3E3,transition_time:1E3,vertical:!0}]});new GuruTwitter({screen_name:"mayfest",trim_user:!0,interval:45E3});c("#gMap").length&&new GuruMap({streetViewControl:!0,fitMarkers:!1,
zoom:16,centerLat:36.153077,centerLng:-95.989392,mapHeight:406,contId:"gMap",locationKey:"mayfest_location_address",markerScale:0.4,markerImageKey:"featured_custom_marker",blocksAreClickable:!0,scrollToMapOnClick:!0,scrollSpeed:450,directionsLink:!0});e()})})(jQuery);
